export default  workersData = [
    {
      id: 1,
      name: "John Doe",
      country: "USA",
      profileImage: "https://randomuser.me/api/portraits/men/1.jpg",
      flagImage: "https://flagcdn.com/w320/us.png",
      category: "Astrologer",
    },
    {
      id: 2,
      name: "Jane Smith",
      country: "Canada",
      profileImage: "https://randomuser.me/api/portraits/women/2.jpg",
      flagImage: "https://flagcdn.com/w320/ca.png",
      category: "Assistant",
    },
    {
      id: 3,
      name: "Mike Johnson",
      country: "UK",
      profileImage: "https://randomuser.me/api/portraits/men/3.jpg",
      flagImage: "https://flagcdn.com/w320/gb.png",
      category: "Makeup",
    },
    {
      id: 4,
      name: "Emily Davis",
      country: "Australia",
      profileImage: "https://randomuser.me/api/portraits/women/4.jpg",
      flagImage: "https://flagcdn.com/w320/au.png",
      category: "Mehndi",
    },
    {
      id: 5,
      name: "Tom Wilson",
      country: "Germany",
      profileImage: "https://randomuser.me/api/portraits/men/5.jpg",
      flagImage: "https://flagcdn.com/w320/de.png",
      category: "Photographer",
    },
    {
      id: 6,
      name: "Anna Brown",
      country: "France",
      profileImage: "https://randomuser.me/api/portraits/women/6.jpg",
      flagImage: "https://flagcdn.com/w320/fr.png",
      category: "Astrologer",
    },
    {
      id: 7,
      name: "David Green",
      country: "Italy",
      profileImage: "https://randomuser.me/api/portraits/men/7.jpg",
      flagImage: "https://flagcdn.com/w320/it.png",
      category: "Assistant",
    },
    {
      id: 8,
      name: "Sophia White",
      country: "Japan",
      profileImage: "https://randomuser.me/api/portraits/women/8.jpg",
      flagImage: "https://flagcdn.com/w320/jp.png",
      category: "Makeup",
    },
    {
      id: 9,
      name: "Liam Harris",
      country: "India",
      profileImage: "https://randomuser.me/api/portraits/men/9.jpg",
      flagImage: "https://flagcdn.com/w320/in.png",
      category: "Mehndi",
    },
    {
      id: 10,
      name: "Olivia Clark",
      country: "Brazil",
      profileImage: "https://randomuser.me/api/portraits/women/10.jpg",
      flagImage: "https://flagcdn.com/w320/br.png",
      category: "Photographer",
    },
    {
      id: 11,
      name: "Noah Young",
      country: "Spain",
      profileImage: "https://randomuser.me/api/portraits/men/11.jpg",
      flagImage: "https://flagcdn.com/w320/es.png",
      category: "Astrologer",
    },
    {
      id: 12,
      name: "Emma Martinez",
      country: "Mexico",
      profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
      flagImage: "https://flagcdn.com/w320/mx.png",
      category: "Assistant",
    },
    {
      id: 13,
      name: "Lucas Robinson",
      country: "Argentina",
      profileImage: "https://randomuser.me/api/portraits/men/13.jpg",
      flagImage: "https://flagcdn.com/w320/ar.png",
      category: "Makeup",
    },
    {
      id: 14,
      name: "Mia Lewis",
      country: "South Korea",
      profileImage: "https://randomuser.me/api/portraits/women/14.jpg",
      flagImage: "https://flagcdn.com/w320/kr.png",
      category: "Mehndi",
    },
    {
      id: 15,
      name: "Ethan Walker",
      country: "South Africa",
      profileImage: "https://randomuser.me/api/portraits/men/15.jpg",
      flagImage: "https://flagcdn.com/w320/za.png",
      category: "Photographer",
    },
    {
      id: 16,
      name: "Charlotte Hall",
      country: "Russia",
      profileImage: "https://randomuser.me/api/portraits/women/16.jpg",
      flagImage: "https://flagcdn.com/w320/ru.png",
      category: "Astrologer",
    },
    {
      id: 17,
      name: "James King",
      country: "Netherlands",
      profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
      flagImage: "https://flagcdn.com/w320/nl.png",
      category: "Assistant",
    },
  ];